version: '3'
services: 
  zoo1:
    image: wurstmeister/zookeeper
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOO_SERVERS: server.1=zoo1:2888:3888
    volumes:
      - /tmp/zoo1/data:/data
      - /tmp/zoo1/datalog:/datalog

  zoonavigator-web:
    image: elkozmon/zoonavigator-web:0.2.3
    ports:
      - "8004:8000"
    environment:
      API_HOST: "zoonavigator-api"
      API_PORT: 9000
    links:
      - zoonavigator-api
    depends_on:
      - zoonavigator-api
    restart: unless-stopped

  zoonavigator-api:
    image: elkozmon/zoonavigator-api:0.2.3
    environment:
      SERVER_HTTP_PORT: 9000
    restart: unless-stopped
    depends_on:
      - zoo1

  kafka1:
    image: wurstmeister/kafka
    hostname: kafka1
    ports:
      - 9092:9092
      - 7203:7203
    environment:
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka1:9092"
      ZOOKEEPER_CONNECTION_STRING: zoo1:2181
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
#      KAFKA_BROKER_ID: 1
      JMX_PORT: 7203
    volumes:
      - /tmp/kafka1/data:/data
      - /tmp/kafka1/logs:/logs
    depends_on:
      - zoo1

  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
      - 9999:9000
    environment:
      ZK_HOSTS: zoo1:2181
      APPLICATION_SECRET: admin
      JMX_PORT: 7203
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka1 -Djava.net.preferIPv4Stack=true"
    links:
      - kafka1
    depends_on:
      - zoo1
      - kafka1
